apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-app2
  labels:
    app: reactjs-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactjs-app2
  template:
    metadata:
      labels:
        app: reactjs-app2
    spec:
      # terminationGracePeriodSeconds: 30
      containers:
      - name: reactjs-app2
        image: rameshkumarverma/reactjs-app2:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
